## Student Name: Gabriel Espinoza Rojas

## Student ID: 22176691

# Task 1

## Task 1.a

Use the following code snippet to download [unigrams](https://www.norvig.com/ngrams/count_1w.txt) and [bigrams](https://www.norvig.com/ngrams/count_2w.txt) data, and load them into their corresponding dataframes, unigrams_df and bigrams_df

In [2]:
#from IPython.core.display import display, HTML
from IPython.display import display, HTML
import pandas as pd


!wget https://norvig.com/ngrams/count_1w.txt #unigram data
!wget https://norvig.com/ngrams/count_2w.txt #bigram data

# remove the . before sending it to Colab/submitting
filePath1 = "./content/count_1w.txt"
filePath2 = "./content/count_2w.txt"


unigrams_df = pd.read_csv(filePath1,sep='\t',header=None, names=['unigram','count'])
bigrams_df = pd.read_csv(filePath2,sep='\t',header=None, names=['bigram','count'])


print(unigrams_df.shape, bigrams_df.shape)
print(f'Number of unigrams: {unigrams_df.shape[0]} Number of Bigrams: {bigrams_df.shape[0]}')  # df.size VS df.shape


display(unigrams_df.head(100),bigrams_df.head(100))

--2026-10-01 01:41:25--  https://norvig.com/ngrams/count_1w.txt
Resolviendo norvig.com (norvig.com)... 158.106.138.13
Conectando con norvig.com (norvig.com)[158.106.138.13]:443... conectado.
Petición HTTP enviada, esperando respuesta... 301 Moved Permanently
Ubicación: https://www.norvig.com/ngrams/count_1w.txt [siguiente]
--2026-10-01 01:41:26--  https://www.norvig.com/ngrams/count_1w.txt
Resolviendo www.norvig.com (www.norvig.com)... 158.106.138.13
Conectando con www.norvig.com (www.norvig.com)[158.106.138.13]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 4956241 (4,7M) [text/plain]
Guardando como: ‘count_1w.txt.1’

count_1w.txt.1      100%[===================>]   4,73M  3,49MB/s    en 1,4s

2026-10-01 01:41:28 (3,49 MB/s) - ‘count_1w.txt.1’ guardado [4956241/4956241]

--2026-10-01 01:41:28--  https://norvig.com/ngrams/count_2w.txt
Resolviendo norvig.com (norvig.com)... 158.106.138.13
Conectando con norvig.com (norvig.com)[158.106.138.13]:443... conectado.
Petición HTTP enviada, esperando respuesta... 301 Moved Permanently
Ubicación: https://www.norvig.com/ngrams/count_2w.txt [siguiente]
--2026-10-01 01:41:29--  https://www.norvig.com/ngrams/count_2w.txt
Resolviendo www.norvig.com (www.norvig.com)... 158.106.138.13
Conectando con www.norvig.com (www.norvig.com)[158.106.138.13]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 5566017 (5,3M) [text/plain]
Guardando como: ‘count_2w.txt.1’

count_2w.txt.1      100%[===================>]   5,31M  2,67MB/s    en 2,0s

2026-10-01 01:41:32 (2,67 MB/s) - ‘count_2w.txt.1’ guardado [5566017/5566017]

(333333, 2) (286358, 2)
Number of unigrams: 333333 Number of Bigrams: 286358

    unigram        count
0       the  23135851162
1        of  13151942776
2       and  12997637966
3        to  12136980858
4         a   9081174698
..      ...          ...
95     like    520585287
96  service    519537222
97        x    508609523
98     than    502609275
99     find    502043038

[100 rows x 2 columns]

               bigram   count
0    0Uplink verified  523545
1              0km to  116103
2            1000s of  939476
3             100s of  539389
4   100th anniversary  158621
..                ...     ...
95            24th of  327460
96   25th anniversary  261023
97            25th of  397735
98            26th of  271707
99            27th of  276619

[100 rows x 2 columns]

## Task 1.b

Complete the function below to compute the probability of a given sentence using the unigram and bigram counts from 1.a. Do not apply add-one smoothing

<b>Expected Output:</b>

```
sentence= ['i', 'love', 'you']

i love

bigram count for "i love" = ?
unigram count for "i" = ?
bigramProbability for "i love" = ?

love you

bigram count for "love you" = ?
unigram count for "love" = ?
bigramProbability for "love you" = ?

sentenceProbability for "i love you" = ?

sentence= ['i', 'hate', 'you']

i hate

bigram count for "i hate" = ?
unigram count for "i" = ?
bigramProbability for "i hate" = ?

hate you

bigram count for "hate you" = ?
unigram count for "hate" = ?
bigramProbability for "hate you" = ?

sentenceProbability for "i hate you" = ?

probability("i love you")>probability("i hate you") is: [True,False]?

sentence= ['OOV1', 'OOV2']

OOV1 OOV2

bigram count for "OOV1 OOV2" = ?
unigram count for "OOV1" = ?
bigramProbability for "OOV1 OOV2" = ?

sentenceProbability for "OOV1 OOV2" = ?
```

In [14]:
def probability(sentence):

    sentence_list = sentence.split(" ")
    
    # part of the expected output
    print(f"sentence= {sentence_list}\n")

    probabilities = []

    for i in range(0, len(sentence_list)-1):
        
        section = sentence_list[i] + " " +sentence_list[i+1]

        # part of the expected output
        print(section+"\n")

        # https://stackoverflow.com/questions/31536835/extract-value-from-single-row-of-pandas-dataframe
        bigram_count = bigrams_df.loc[bigrams_df['bigram'] == section]['count'].values
        unigram_count = unigrams_df.loc[unigrams_df['unigram'] == sentence_list[i]]['count'].values

        # I had to add logic to avoid errors when the words are not found in the txt files
        # https://stackoverflow.com/questions/5086178/how-to-check-if-array-is-not-empty
        bigram_count = bigram_count[0] if bigram_count.size else 0
        unigram_count = unigram_count[0] if unigram_count.size else 0
       
        print(f"bigram count for \"{section}\" = {bigram_count}")
        print(f"unigram count for \"{sentence_list[i]}\" = {unigram_count}")

        # https://youtu.be/UyC0bBiZY-A?t=16 P(w_i | w_i-1) = count(W_i-1, w_i) / count(W_i-1)
        bigram_probability = bigram_count / unigram_count if unigram_count != 0 else 0
        print(f"bigramProbability for \"{section}\" = {bigram_probability}\n")

        probabilities = probabilities + [bigram_probability]


    """
    Example from chapter 3, bigram
    P(<s> i want english food </s>) =   P(i|<s>)*P(want|i)*P(english|want)*P(food|english)*P(</s>|food)
                                    =   0.25*0.33*0.0011*0.5*0.68
                                    =   0.000031
    """
    sentence_probability = 1
    for probability in probabilities:
        sentence_probability = sentence_probability * probability
    print(f"sentenceProbability for \"{sentence}\" {sentence_probability}\n")
    return sentence_probability

#TESTING
probA = probability("i love you")
brobB = probability('i hate you')
#probability("i love you")>probability("i hate you") is: [True,False]?
print(f'probability("i love you")>probability("i hate you") is: {probA>brobB}\n')
probability("OOV1 OOV2") # Test for OOV (Out Of Vocabulary) N-grams

sentence= ['i', 'love', 'you']

i love

bigram count for "i love" = 3979312
unigram count for "i" = 3086225277
bigramProbability for "i love" = 0.001289378332053626

love you

bigram count for "love you" = 5428714
unigram count for "love" = 201063526
bigramProbability for "love you" = 0.02699999402178991

sentenceProbability for "i love you" 3.481320725727335e-05

sentence= ['i', 'hate', 'you']

i hate

bigram count for "i hate" = 876611
unigram count for "i" = 3086225277
bigramProbability for "i hate" = 0.0002840398614232463

hate you

bigram count for "hate you" = 504048
unigram count for "hate" = 21274675
bigramProbability for "hate you" = 0.023692394830943365

sentenceProbability for "i hate you" 6.7295845445659906e-06

probability("i love you")>probability("i hate you") is: True

sentence= ['OOV1', 'OOV2']

OOV1 OOV2

bigram count for "OOV1 OOV2" = 0
unigram count for "OOV1" = 0
bigramProbability for "OOV1 OOV2" = 0

sentenceProbability for "OOV1 OOV2" 0

0

## Task 1.c

Copy the function from 1.b into a new code cell, and modify it such that it applies add-one smoothing. Your new function should also address the problem of underflow when computing a sentence Probability

In [15]:
"""
from the book:
3.6.1 Laplace Smoothing
The simplest way to do smoothing is to add one to all the n-gram counts, before we normalize them into probabilities. 

https://youtu.be/Hr6UWRwAIEQ?list=PLAUFqkTvH_MQ&t=73
"""

def probability(sentence):

    sentence_list = sentence.split(" ")
    
    # part of the expected output
    print(f"sentence= {sentence_list}\n")

    probabilities = []

    for i in range(0, len(sentence_list)-1):
        
        section = sentence_list[i] + " " +sentence_list[i+1]

        # part of the expected output
        print(section+"\n")

        # https://stackoverflow.com/questions/31536835/extract-value-from-single-row-of-pandas-dataframe
        bigram_count = bigrams_df.loc[bigrams_df['bigram'] == section]['count'].values
        unigram_count = unigrams_df.loc[unigrams_df['unigram'] == sentence_list[i]]['count'].values

        

        # I had to add logic to avoid errors when the words are not found in the txt files
        # https://stackoverflow.com/questions/5086178/how-to-check-if-array-is-not-empty
        bigram_count = bigram_count[0] if bigram_count.size else 0
        unigram_count = unigram_count[0] if unigram_count.size else 0
       
        print(f"bigram count for \"{section}\" = {bigram_count}")
        print(f"unigram count for \"{sentence_list[i]}\" = {unigram_count}")

        laplace_smoothing = 1
        V = len(unigrams_df)
        # idk if the laplace goes here or in the probability
        # the book computes the probability as 
        # P_laplace(Wn|Wn-1) = C(Wn-1 Wn) + 1 / sum_w (C(Wn-1 W) + 1) = C(Wn-1 Wn) + 1 / C(Wn-1) + V
        # https://youtu.be/UyC0bBiZY-A?t=16 P(w_i | w_i-1) = count(W_i-1, w_i) / count(W_i-1)
        bigram_probability = (bigram_count + laplace_smoothing) / (unigram_count + V)
        print(f"bigramProbability for \"{section}\" = {bigram_probability}\n")

        probabilities = probabilities + [bigram_probability]

    sentence_probability = 1
    for probability in probabilities:
        sentence_probability = sentence_probability * probability
    print(f"sentenceProbability for \"{sentence}\" {sentence_probability}\n")
    return sentence_probability

#TESTING
probA = probability("i love you")
brobB = probability('i hate you')
#probability("i love you")>probability("i hate you") is: [True,False]?
print(f'probability("i love you")>probability("i hate you") is: {probA>brobB}\n')
probability("OOV1 OOV2") # Test for OOV (Out Of Vocabulary) N-grams

sentence= ['i', 'love', 'you']

i love

bigram count for "i love" = 3979312
unigram count for "i" = 3086225277
bigramProbability for "i love" = 0.001289239409583089

love you

bigram count for "love you" = 5428714
unigram count for "love" = 201063526
bigramProbability for "love you" = 0.026955311155076156

sentenceProbability for "i love you" 3.475184943869884e-05

sentence= ['i', 'hate', 'you']

i hate

bigram count for "i hate" = 876611
unigram count for "i" = 3086225277
bigramProbability for "i hate" = 0.00028400951051436537

hate you

bigram count for "hate you" = 504048
unigram count for "hate" = 21274675
bigramProbability for "hate you" = 0.023326953599795038

sentenceProbability for "i hate you" 6.625076673669102e-06

probability("i love you")>probability("i hate you") is: True

sentence= ['OOV1', 'OOV2']

OOV1 OOV2

bigram count for "OOV1 OOV2" = 0
unigram count for "OOV1" = 0
bigramProbability for "OOV1 OOV2" = 3.000003000003e-06

sentenceProbability for "OOV1 OOV2" 3.000003000003e-06

3.000003000003e-06

In [16]:
#I need to test underflow, the core material suggests using log
probability("You met me at a very strange time in my life")

sentence= ['You', 'met', 'me', 'at', 'a', 'very', 'strange', 'time', 'in', 'my', 'life']

You met

bigram count for "You met" = 0
unigram count for "You" = 0
bigramProbability for "You met" = 3.000003000003e-06

met me

bigram count for "met me" = 153123
unigram count for "met" = 42223443
bigramProbability for "met me" = 0.0035981109095294247

me at

bigram count for "me at" = 5511140
unigram count for "me" = 566617666
bigramProbability for "me at" = 0.009720665471479309

at a

bigram count for "at a" = 78330475
unigram count for "at" = 2272272772
bigramProbability for "at a" = 0.03446724701991417

a very

bigram count for "a very" = 47769499
unigram count for "a" = 9081174698
bigramProbability for "a very" = 0.005260084540688328

very strange

bigram count for "very strange" = 516164
unigram count for "very" = 334923368
bigramProbability for "very strange" = 0.0015396112843095715

strange time

bigram count for "strange time" = 0
unigram count for "strange" = 18322738
bigramProbability for "strange time" = 5.360185432398923e-08

time in

bigram count for "time in" = 15124413
unigram count for "time" = 908705570
bigramProbability for "time in" = 0.01663780719404481

in my

bigram count for "in my" = 47618595
unigram count for "in" = 8469404971
bigramProbability for "in my" = 0.005622203932500628

my life

bigram count for "my life" = 12053115
unigram count for "my" = 1059793441
bigramProbability for "my life" = 0.011369504379671483

sentenceProbability for "You met me at a very strange time in my life" 1.6696547150044512e-30

np.float64(1.6696547150044512e-30)

In [17]:
probability("You met me at a very chinese time in my life")

sentence= ['You', 'met', 'me', 'at', 'a', 'very', 'chinese', 'time', 'in', 'my', 'life']

You met

bigram count for "You met" = 0
unigram count for "You" = 0
bigramProbability for "You met" = 3.000003000003e-06

met me

bigram count for "met me" = 153123
unigram count for "met" = 42223443
bigramProbability for "met me" = 0.0035981109095294247

me at

bigram count for "me at" = 5511140
unigram count for "me" = 566617666
bigramProbability for "me at" = 0.009720665471479309

at a

bigram count for "at a" = 78330475
unigram count for "at" = 2272272772
bigramProbability for "at a" = 0.03446724701991417

a very

bigram count for "a very" = 47769499
unigram count for "a" = 9081174698
bigramProbability for "a very" = 0.005260084540688328

very chinese

bigram count for "very chinese" = 0
unigram count for "very" = 334923368
bigramProbability for "very chinese" = 2.9827890002413406e-09

chinese time

bigram count for "chinese time" = 0
unigram count for "chinese" = 56057597
bigramProbability for "chinese time" = 1.773334825299033e-08

time in

bigram count for "time in" = 15124413
unigram count for "time" = 908705570
bigramProbability for "time in" = 0.01663780719404481

in my

bigram count for "in my" = 47618595
unigram count for "in" = 8469404971
bigramProbability for "in my" = 0.005622203932500628

my life

bigram count for "my life" = 12053115
unigram count for "my" = 1059793441
bigramProbability for "my life" = 0.011369504379671483

sentenceProbability for "You met me at a very chinese time in my life" 1.0701608140445632e-36

np.float64(1.0701608140445632e-36)

In [ ]:
#I need to test underflow, the core material suggests using log
probability("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way")

sentence= ['It', 'was', 'the', 'best', 'of', 'times,', 'it', 'was', 'the', 'worst', 'of', 'times,', 'it', 'was', 'the', 'age', 'of', 'wisdom,', 'it', 'was', 'the', 'age', 'of', 'foolishness,', 'it', 'was', 'the', 'epoch', 'of', 'belief,', 'it', 'was', 'the', 'epoch', 'of', 'incredulity,', 'it', 'was', 'the', 'season', 'of', 'Light,', 'it', 'was', 'the', 'season', 'of', 'Darkness,', 'it', 'was', 'the', 'spring', 'of', 'hope,', 'it', 'was', 'the', 'winter', 'of', 'despair,', 'we', 'had', 'everything', 'before', 'us,', 'we', 'had', 'nothing', 'before', 'us,', 'we', 'were', 'all', 'going', 'direct', 'to', 'Heaven,', 'we', 'were', 'all', 'going', 'direct', 'the', 'other', 'way']

It was

bigram count for "It was" = 58039544
unigram count for "It" = 0
bigramProbability for "It was" = 174.1188091188091

was the

bigram count for "was the" = 65694274
unigram count for "was" = 1483428678
bigramProbability for "was the" = 0.044275479836368446

the best

bigram count for "the best" = 109363237
unigram count for "the" = 23135851162
bigramProbability for "the best" = 0.004726934902495901

best of

bigram count for "best of" = 10655810
unigram count for "best" = 371852748
bigramProbability for "best of" = 0.028630331825869652

of times,

bigram count for "of times," = 0
unigram count for "of" = 13151942776
bigramProbability for "of times," = 7.603246705836017e-11

times, it

bigram count for "times, it" = 0
unigram count for "times," = 0
bigramProbability for "times, it" = 3.000003000003e-06

it was

bigram count for "it was" = 117973454
unigram count for "it" = 2813163874
bigramProbability for "it was" = 0.041931250084940995

was the

bigram count for "was the" = 65694274
unigram count for "was" = 1483428678
bigramProbability for "was the" = 0.044275479836368446

the worst

bigram count for "the worst" = 7082164
unigram count for "the" = 23135851162
bigramProbability for "the worst" = 0.00030610773360363456

worst of

bigram count for "worst of" = 846907
unigram count for "worst" = 16975343
bigramProbability for "worst of" = 0.04892968127660371

of times,

bigram count for "of times," = 0
unigram count for "of" = 13151942776
bigramProbability for "of times," = 7.603246705836017e-11

times, it

bigram count for "times, it" = 0
unigram count for "times," = 0
bigramProbability for "times, it" = 3.000003000003e-06

it was

bigram count for "it was" = 117973454
unigram count for "it" = 2813163874
bigramProbability for "it was" = 0.041931250084940995

was the

bigram count for "was the" = 65694274
unigram count for "was" = 1483428678
bigramProbability for "was the" = 0.044275479836368446

the age

bigram count for "the age" = 11093277
unigram count for "the" = 23135851162
bigramProbability for "the age" = 0.000479477417825631

age of

bigram count for "age of" = 12304538
unigram count for "age" = 132725767
bigramProbability for "age of" = 0.09247423889083874

of wisdom,

bigram count for "of wisdom," = 0
unigram count for "of" = 13151942776
bigramProbability for "of wisdom," = 7.603246705836017e-11

wisdom, it

bigram count for "wisdom, it" = 0
unigram count for "wisdom," = 0
bigramProbability for "wisdom, it" = 3.000003000003e-06

it was

bigram count for "it was" = 117973454
unigram count for "it" = 2813163874
bigramProbability for "it was" = 0.041931250084940995

was the

bigram count for "was the" = 65694274
unigram count for "was" = 1483428678
bigramProbability for "was the" = 0.044275479836368446

the age

bigram count for "the age" = 11093277
unigram count for "the" = 23135851162
bigramProbability for "the age" = 0.000479477417825631

age of

bigram count for "age of" = 12304538
unigram count for "age" = 132725767
bigramProbability for "age of" = 0.09247423889083874

of foolishness,

bigram count for "of foolishness," = 0
unigram count for "of" = 13151942776
bigramProbability for "of foolishness," = 7.603246705836017e-11

foolishness, it

bigram count for "foolishness, it" = 0
unigram count for "foolishness," = 0
bigramProbability for "foolishness, it" = 3.000003000003e-06

it was

bigram count for "it was" = 117973454
unigram count for "it" = 2813163874
bigramProbability for "it was" = 0.041931250084940995

was the

bigram count for "was the" = 65694274
unigram count for "was" = 1483428678
bigramProbability for "was the" = 0.044275479836368446

the epoch

bigram count for "the epoch" = 119027
unigram count for "the" = 23135851162
bigramProbability for "the epoch" = 5.144668518083582e-06

epoch of

bigram count for "epoch of" = 103118
unigram count for "epoch" = 1680235
bigramProbability for "epoch of" = 0.05121207726781514

of belief,

bigram count for "of belief," = 0
unigram count for "of" = 13151942776
bigramProbability for "of belief," = 7.603246705836017e-11

belief, it

bigram count for "belief, it" = 0
unigram count for "belief," = 0
bigramProbability for "belief, it" = 3.000003000003e-06

it was

bigram count for "it was" = 117973454
unigram count for "it" = 2813163874
bigramProbability for "it was" = 0.041931250084940995

was the

bigram count for "was the" = 65694274
unigram count for "was" = 1483428678
bigramProbability for "was the" = 0.044275479836368446

the epoch

bigram count for "the epoch" = 119027
unigram count for "the" = 23135851162
bigramProbability for "the epoch" = 5.144668518083582e-06

epoch of

bigram count for "epoch of" = 103118
unigram count for "epoch" = 1680235
bigramProbability for "epoch of" = 0.05121207726781514

of incredulity,

bigram count for "of incredulity," = 0
unigram count for "of" = 13151942776
bigramProbability for "of incredulity," = 7.603246705836017e-11

incredulity, it

bigram count for "incredulity, it" = 0
unigram count for "incredulity," = 0
bigramProbability for "incredulity, it" = 3.000003000003e-06

it was

bigram count for "it was" = 117973454
unigram count for "it" = 2813163874
bigramProbability for "it was" = 0.041931250084940995

was the

bigram count for "was the" = 65694274
unigram count for "was" = 1483428678
bigramProbability for "was the" = 0.044275479836368446

the season

bigram count for "the season" = 7258192
unigram count for "the" = 23135851162
bigramProbability for "the season" = 0.00031371607542153633

season of

bigram count for "season of" = 1321580
unigram count for "season" = 76445684
bigramProbability for "season of" = 0.017212788749301128

of Light,

bigram count for "of Light," = 0
unigram count for "of" = 13151942776
bigramProbability for "of Light," = 7.603246705836017e-11

Light, it

bigram count for "Light, it" = 0
unigram count for "Light," = 0
bigramProbability for "Light, it" = 3.000003000003e-06

it was

bigram count for "it was" = 117973454
unigram count for "it" = 2813163874
bigramProbability for "it was" = 0.041931250084940995

was the

bigram count for "was the" = 65694274
unigram count for "was" = 1483428678
bigramProbability for "was the" = 0.044275479836368446

the season

bigram count for "the season" = 7258192
unigram count for "the" = 23135851162
bigramProbability for "the season" = 0.00031371607542153633

season of

bigram count for "season of" = 1321580
unigram count for "season" = 76445684
bigramProbability for "season of" = 0.017212788749301128

of Darkness,

bigram count for "of Darkness," = 0
unigram count for "of" = 13151942776
bigramProbability for "of Darkness," = 7.603246705836017e-11

Darkness, it

bigram count for "Darkness, it" = 0
unigram count for "Darkness," = 0
bigramProbability for "Darkness, it" = 3.000003000003e-06

it was

bigram count for "it was" = 117973454
unigram count for "it" = 2813163874
bigramProbability for "it was" = 0.041931250084940995

was the

bigram count for "was the" = 65694274
unigram count for "was" = 1483428678
bigramProbability for "was the" = 0.044275479836368446

the spring

bigram count for "the spring" = 4259178
unigram count for "the" = 23135851162
bigramProbability for "the spring" = 0.00018409167686748255

spring of

bigram count for "spring of" = 1451049
unigram count for "spring" = 64814116
bigramProbability for "spring of" = 0.02227332032601921

of hope,

bigram count for "of hope," = 0
unigram count for "of" = 13151942776
bigramProbability for "of hope," = 7.603246705836017e-11

hope, it

bigram count for "hope, it" = 0
unigram count for "hope," = 0
bigramProbability for "hope, it" = 3.000003000003e-06

it was

bigram count for "it was" = 117973454
unigram count for "it" = 2813163874
bigramProbability for "it was" = 0.041931250084940995

was the

bigram count for "was the" = 65694274
unigram count for "was" = 1483428678
bigramProbability for "was the" = 0.044275479836368446

the winter

bigram count for "the winter" = 4089346
unigram count for "the" = 23135851162
bigramProbability for "the winter" = 0.00017675114065950485

winter of

bigram count for "winter of" = 451628
unigram count for "winter" = 51483174
bigramProbability for "winter of" = 0.008715929076423466

of despair,

bigram count for "of despair," = 0
unigram count for "of" = 13151942776
bigramProbability for "of despair," = 7.603246705836017e-11

despair, we

bigram count for "despair, we" = 0
unigram count for "despair," = 0
bigramProbability for "despair, we" = 3.000003000003e-06

we had

bigram count for "we had" = 15173882
unigram count for "we" = 1390661912
bigramProbability for "we had" = 0.010908651955887886

had everything

bigram count for "had everything" = 220678
unigram count for "had" = 480232730
bigramProbability for "had everything" = 0.0004592063755446668

everything before

bigram count for "everything before" = 0
unigram count for "everything" = 91388083
bigramProbability for "everything before" = 1.0902579175184125e-08

before us,

bigram count for "before us," = 0
unigram count for "before" = 277546019
bigramProbability for "before us," = 3.5986840792690492e-09

us, we

bigram count for "us, we" = 0
unigram count for "us," = 0
bigramProbability for "us, we" = 3.000003000003e-06

we had

bigram count for "we had" = 15173882
unigram count for "we" = 1390661912
bigramProbability for "we had" = 0.010908651955887886

had nothing

bigram count for "had nothing" = 1275591
unigram count for "had" = 480232730
bigramProbability for "had nothing" = 0.0026543530602992247

nothing before

bigram count for "nothing before" = 0
unigram count for "nothing" = 73183983
bigramProbability for "nothing before" = 1.3602237600730691e-08

before us,

bigram count for "before us," = 0
unigram count for "before" = 277546019
bigramProbability for "before us," = 3.5986840792690492e-09

us, we

bigram count for "us, we" = 0
unigram count for "us," = 0
bigramProbability for "us, we" = 3.000003000003e-06

we were

bigram count for "we were" = 22209977
unigram count for "we" = 1390661912
bigramProbability for "we were" = 0.015966969031587164

were all

bigram count for "were all" = 4718342
unigram count for "were" = 570699558
bigramProbability for "were all" = 0.008262821764499726

all going

bigram count for "all going" = 413841
unigram count for "all" = 2022459848
bigramProbability for "all going" = 0.000204589378631092

going direct

bigram count for "going direct" = 0
unigram count for "going" = 155284081
bigramProbability for "going direct" = 6.426016049849023e-09

direct to

bigram count for "direct to" = 1880700
unigram count for "direct" = 102234090
bigramProbability for "direct to" = 0.018336241127945664

to Heaven,

bigram count for "to Heaven," = 0
unigram count for "to" = 12136980858
bigramProbability for "to Heaven," = 8.239055068225184e-11

Heaven, we

bigram count for "Heaven, we" = 0
unigram count for "Heaven," = 0
bigramProbability for "Heaven, we" = 3.000003000003e-06

we were

bigram count for "we were" = 22209977
unigram count for "we" = 1390661912
bigramProbability for "we were" = 0.015966969031587164

were all

bigram count for "were all" = 4718342
unigram count for "were" = 570699558
bigramProbability for "were all" = 0.008262821764499726

all going

bigram count for "all going" = 413841
unigram count for "all" = 2022459848
bigramProbability for "all going" = 0.000204589378631092

going direct

bigram count for "going direct" = 0
unigram count for "going" = 155284081
bigramProbability for "going direct" = 6.426016049849023e-09

direct the

bigram count for "direct the" = 1351968
unigram count for "direct" = 102234090
bigramProbability for "direct the" = 0.013181271016236803

the other

bigram count for "the other" = 79925407
unigram count for "the" = 23135851162
bigramProbability for "the other" = 0.0034545630467838298

other way

bigram count for "other way" = 2846796
unigram count for "other" = 978481319
bigramProbability for "other way" = 0.002908412735938489

sentenceProbability for "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way" 0.0

np.float64(0.0)

# Task 2

Using the [bigram counts](https://www.norvig.com/ngrams/count_2w.txt) (bigrams_df), write a function that implements the Shannon visualisation method:

<!--<b>Expected Output:</b>-->

```
<s> I
    I want
        want to
             to eat
                eat Chinese
                    Chinese food
                            food </s>

I want to eat Chinese food
```

[Chapter 3, section 3.4](https://web.stanford.edu/~jurafsky/slp3/3.pdf) gives a detailed description of the Shannon Visualisation method; a screenshot of this section is provided below. If you can follow the logic applied to unigrams, then you should be able to apply the same logic to bigrams.

Note: given the large size of the bigrams data, the Shannon Visualisation sampling can continue for a long time; therefore, for initial testing, you could terminate the sampling early whenever a common word (e.g. “and”) is generated as the next new seed.

Extra Help: 
- The seed word can be any word, but let's stick to the default seed word `<S>`, which indicates the beginning of the sentence. 
- First, you need to retrieve a list of all the bigrams starting with `<S>`, and then <u>randomly select one of them according to its probability</u>. Understanding this last part is key! You have a probability space between 0 and 1, and each of the candidate bigrams covers <u>an interval in this space proportional to its frequency</u>. For example, the candidate bigram “`<S>` and” has a total frequency of 261891475, which translates to a probability of 0.031513. If you consider this bigram to be your first candidate, then you can assign the probability interval 0.0 to 0.031513 to it. There are 8640 bigrams in the dataset which start with `<S>` and you need to compute the probability intervals for all of them. 
- Then generate a random number between 0 and 1 and check to see which interval it falls into; that would be your chosen bigram.
- Pick the second word in the chosen bigram, and that would be your new seed word.
- This process should be repeated until you either reach `</S>` (indicating the end of the sentence) or come across a seed which does not exist in your list of bigrams (i.e. there is no bigram starting with this seed word).

In [ ]:
import random

def ShannonVisualization(full_sentence="", seed="<S>"):

    # this is never going to happen because </S> is not part of the e-tivity corpus
    # however, other datasets may have it since it is a common practice to use it as the ending token
    if seed == "</S>":
        return full_sentence
    
    # get all the bigrams starting with the seed word
    bigrams_starting_with_seed_word_df = bigrams_df.loc[bigrams_df['bigram'].str.contains("^" + seed + " ")]
    
    # resetting the index to avoid any confusions (not sure if this is the best way to go or adding a table and appending the probability to each row would be better)
    bigrams_starting_with_seed_word_df = bigrams_starting_with_seed_word_df.reset_index()

    # this will hold the sum of all bigrams' counts with the seed word
    full_count = 0
    for index, row in bigrams_starting_with_seed_word_df.iterrows():
        full_count = full_count + row['count']

    if full_count == 0:
        # a seed which does not exist in your list of bigrams (i.e. there is no bigram starting with this seed word).
        return full_sentence

    probabilities = []

    for index, row in bigrams_starting_with_seed_word_df.iterrows():
        probabilities = probabilities + [row['count']/full_count]

    # this will hold the sum of probabilities
    cumulative_probabilities = 0

     # this is the number between 0 and 1 that will decide the starting bigram
    random_pick = random.random()
    
    # this loop will increment the probability until it is greater than the random number, this is how we find the selected bigram and thefore the next seed
    for index, probability in enumerate(probabilities):

        cumulative_probabilities = cumulative_probabilities + probability
        
        if random_pick < cumulative_probabilities:

            # setting the amount of spacing accordingly to give that waterfall effect
            print( " "*len(full_sentence) + bigrams_starting_with_seed_word_df.iloc[index]['bigram'])
            next_seed = bigrams_starting_with_seed_word_df.iloc[index]['bigram'].split(" ")[1]

            #recursion since it is a recurrent theme in the module
            return ShannonVisualization(full_sentence + next_seed + " ", next_seed)


final_sentence = ShannonVisualization()
print(final_sentence)

<S> login
      login name
           name on
              on project
                      project that
                           that exists
                                  exists with
                                       with the
                                           the agreements
                                                      agreements between
                                                              between the
                                                                  the entire
                                                                         entire universe
                                                                                  universe of
                                                                                     of a
                                                                                       a reputable
                                                                                                 reputable companies
                                                                                                           companies house
                                                                                                                 house down
                                                                                                                      down on
                                                                                                                         on the
                                                                                                                             the nation
                                                                                                                                    nation or
                                                                                                                                       or eliminate
                                                                                                                                                 eliminate any
                                                                                                                                                     any other
                                                                                                                                                           other visitors
                                                                                                                                                                    visitors who
                                                                                                                                                                        who looks
                                                                                                                                                                              looks like
                                                                                                                                                                                   like a
                                                                                                                                                                                     a lie
                                                                                                                                                                                         lie ahead
                                                                                                                                                                                               ahead of
                                                                                                                                                                                                  of the
                                                                                                                                                                                                      the aerial
                                                                                                                                                                                                             aerial photo
                                                                                                                                                                                                                   photo images
                                                                                                                                                                                                                          images will
                                                                                                                                                                                                                               will decrease
                                                                                                                                                                                                                                        decrease in
                                                                                                                                                                                                                                           in for
                                                                                                                                                                                                                                               for my
                                                                                                                                                                                                                                                  my opinion
                                                                                                                                                                                                                                                          opinion expressed
                                                                                                                                                                                                                                                                    expressed a
                                                                                                                                                                                                                                                                      a a
                                                                                                                                                                                                                                                                        a lifetime
                                                                                                                                                                                                                                                                                 lifetime and
                                                                                                                                                                                                                                                                                     and being
                                                                                                                                                                                                                                                                                           being an
                                                                                                                                                                                                                                                                                              an alley
login name on project that exists with the agreements between the entire universe of a reputable companies house down on the nation or eliminate any other visitors who looks like a lie ahead of the aerial photo images will decrease in for my opinion expressed a a lifetime and being an alley