## Student Name: Gabriel Espinoza Rojas

## Student ID: 22176691

# Task 1

## Task 1.a

Use the following code snippet to download [unigrams](https://www.norvig.com/ngrams/count_1w.txt) and [bigrams](https://www.norvig.com/ngrams/count_2w.txt) data, and load them into their corresponding dataframes, unigrams_df and bigrams_df

In [2]:
#from IPython.core.display import display, HTML
from IPython.display import display, HTML
import pandas as pd


!wget https://norvig.com/ngrams/count_1w.txt #unigram data
!wget https://norvig.com/ngrams/count_2w.txt #bigram data


filePath1 = "/content/count_1w.txt"
filePath2 = "/content/count_2w.txt"


unigrams_df = pd.read_csv(filePath1,sep='\t',header=None, names=['unigram','count'])
bigrams_df = pd.read_csv(filePath2,sep='\t',header=None, names=['bigram','count'])


print(unigrams_df.shape, bigrams_df.shape)
print(f'Number of unigrams: {unigrams_df.shape[0]} Number of Bigrams: {bigrams_df.shape[0]}')  # df.size VS df.shape


display(unigrams_df.head(100),bigrams_df.head(100))

--2026-09-26 23:04:24--  https://norvig.com/ngrams/count_1w.txt
Resolving norvig.com (norvig.com)... 158.106.138.13
Connecting to norvig.com (norvig.com)|158.106.138.13|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.norvig.com/ngrams/count_1w.txt [following]
--2026-09-26 23:04:25--  https://www.norvig.com/ngrams/count_1w.txt
Resolving www.norvig.com (www.norvig.com)... 158.106.138.13
Connecting to www.norvig.com (www.norvig.com)|158.106.138.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4956241 (4.7M) [text/plain]
Saving to: ‘count_1w.txt.1’

count_1w.txt.1      100%[===================>]   4.73M  5.87MB/s    in 0.8s

2026-09-26 23:04:26 (5.87 MB/s) - ‘count_1w.txt.1’ saved [4956241/4956241]

--2026-09-26 23:04:26--  https://norvig.com/ngrams/count_2w.txt
Resolving norvig.com (norvig.com)... 158.106.138.13
Connecting to norvig.com (norvig.com)|158.106.138.13|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.norvig.com/ngrams/count_2w.txt [following]
--2026-09-26 23:04:27--  https://www.norvig.com/ngrams/count_2w.txt
Resolving www.norvig.com (www.norvig.com)... 158.106.138.13
Connecting to www.norvig.com (www.norvig.com)|158.106.138.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5566017 (5.3M) [text/plain]
Saving to: ‘count_2w.txt.1’

count_2w.txt.1      100%[===================>]   5.31M  6.55MB/s    in 0.8s

2026-09-26 23:04:28 (6.55 MB/s) - ‘count_2w.txt.1’ saved [5566017/5566017]

(333333, 2) (286358, 2)
Number of unigrams: 333333 Number of Bigrams: 286358

    unigram        count
0       the  23135851162
1        of  13151942776
2       and  12997637966
3        to  12136980858
4         a   9081174698
..      ...          ...
95     like    520585287
96  service    519537222
97        x    508609523
98     than    502609275
99     find    502043038

[100 rows x 2 columns]

               bigram   count
0    0Uplink verified  523545
1              0km to  116103
2            1000s of  939476
3             100s of  539389
4   100th anniversary  158621
..                ...     ...
95            24th of  327460
96   25th anniversary  261023
97            25th of  397735
98            26th of  271707
99            27th of  276619

[100 rows x 2 columns]

## Task 1.b

Complete the function below to compute the probability of a given sentence using the unigram and bigram counts from (a). Do not apply add-one smoothing

<b>Expected Output:</b>

```
sentence= ['i', 'love', 'you']

i love

bigram count for "i love" = ?
unigram count for "i" = ?
bigramProbability for "i love" = ?

love you

bigram count for "love you" = ?
unigram count for "love" = ?
bigramProbability for "love you" = ?

sentenceProbability for "i love you" = ?

sentence= ['i', 'hate', 'you']

i hate

bigram count for "i hate" = ?
unigram count for "i" = ?
bigramProbability for "i hate" = ?

hate you

bigram count for "hate you" = ?
unigram count for "hate" = ?
bigramProbability for "hate you" = ?

sentenceProbability for "i hate you" = ?

probability("i love you")>probability("i hate you") is: [True,False]?

sentence= ['OOV1', 'OOV2']

OOV1 OOV2

bigram count for "OOV1 OOV2" = ?
unigram count for "OOV1" = ?
bigramProbability for "OOV1 OOV2" = ?

sentenceProbability for "OOV1 OOV2" = ?
```

In [4]:
def probability(sentence):
    print("YOUR CODE HERE")
    return 1


#TESTING
probA = probability("i love you")
brobB = probability('i hate you')
print(f'probability("i love you")>probability("i hate you") is: {probA>brobB}\n')
probability("OOV1 OOV2") # Test for OOV (Out Of Vocabulary) N-grams

YOUR CODE HERE
YOUR CODE HERE
probability("i love you")>probability("i hate you") is: False

YOUR CODE HERE

1

## Task 1.c

Copy the function from (b) into a new code cell, and modify it such that it applies add-one smoothing. Your new function should also address the problem of underflow when computing a sentence Probability

# Task 2

Using the [bigram counts](https://www.norvig.com/ngrams/count_2w.txt) (bigrams_df), write a function that implements the Shannon visualisation method:

<!--<b>Expected Output:</b>-->

```
<s> I
    I want
        want to
             to eat
                eat Chinese
                    Chinese food
                            food </s>

I want to eat Chinese food
```

[Chapter 3, section 3.4](https://web.stanford.edu/~jurafsky/slp3/3.pdf) gives a detailed description of the Shannon Visualisation method; a screenshot of this section is provided below. If you can follow the logic applied to unigrams, then you should be able to apply the same logic to bigrams.

Note: given the large size of the bigrams data, the Shannon Visualisation sampling can continue for a long time; therefore, for initial testing, you could terminate the sampling early whenever a common word (e.g. “and”) is generated as the next new seed.

Extra Help: 
- The seed word can be any word, but let's stick to the default seed word `<S>`, which indicates the beginning of the sentence. 
- First, you need to retrieve a list of all the bigrams starting with `<S>`, and then <u>randomly select one of them according to its probability</u>. Understanding this last part is key! You have a probability space between 0 and 1, and each of the candidate bigrams covers <u>an interval in this space proportional to its frequency</u>. For example, the candidate bigram “`<S>` and” has a total frequency of 261891475, which translates to a probability of 0.031513. If you consider this bigram to be your first candidate, then you can assign the probability interval 0.0 to 0.031513 to it. There are 8640 bigrams in the dataset which start with `<S>` and you need to compute the probability intervals for all of them. 
- Then generate a random number between 0 and 1 and check to see which interval it falls into; that would be your chosen bigram.
- Pick the second word in the chosen bigram, and that would be your new seed word.
- This process should be repeated until you either reach `</S>` (indicating the end of the sentence) or come across a seed which does not exist in your list of bigrams (i.e. there is no bigram starting with this seed word).

In [ ]:
def ShannonVisualization(seed="<S>"):
    print("YOUR CODE HERE")