## Student Name: Gabriel Espinoza Rojas

## Student ID: 22176691

# Task 1

## Task 1.a

Use the following code snippet to download [unigrams](https://www.norvig.com/ngrams/count_1w.txt) and [bigrams](https://www.norvig.com/ngrams/count_2w.txt) data, and load them into their corresponding dataframes, unigrams_df and bigrams_df

In [2]:
#from IPython.core.display import display, HTML
from IPython.display import display, HTML
import pandas as pd


!wget https://norvig.com/ngrams/count_1w.txt #unigram data
!wget https://norvig.com/ngrams/count_2w.txt #bigram data

# remove the . before sending it to Colab/submitting
filePath1 = "./content/count_1w.txt"
filePath2 = "./content/count_2w.txt"


unigrams_df = pd.read_csv(filePath1,sep='\t',header=None, names=['unigram','count'])
bigrams_df = pd.read_csv(filePath2,sep='\t',header=None, names=['bigram','count'])


print(unigrams_df.shape, bigrams_df.shape)
print(f'Number of unigrams: {unigrams_df.shape[0]} Number of Bigrams: {bigrams_df.shape[0]}')  # df.size VS df.shape


display(unigrams_df.head(100),bigrams_df.head(100))

'wget' is not recognized as an internal or external command,
operable program or batch file.
'wget' is not recognized as an internal or external command,
operable program or batch file.

(333333, 2) (286358, 2)
Number of unigrams: 333333 Number of Bigrams: 286358

    unigram        count
0       the  23135851162
1        of  13151942776
2       and  12997637966
3        to  12136980858
4         a   9081174698
..      ...          ...
95     like    520585287
96  service    519537222
97        x    508609523
98     than    502609275
99     find    502043038

[100 rows x 2 columns]

               bigram   count
0    0Uplink verified  523545
1              0km to  116103
2            1000s of  939476
3             100s of  539389
4   100th anniversary  158621
..                ...     ...
95            24th of  327460
96   25th anniversary  261023
97            25th of  397735
98            26th of  271707
99            27th of  276619

[100 rows x 2 columns]

## Task 1.b

Complete the function below to compute the probability of a given sentence using the unigram and bigram counts from 1.a. Do not apply add-one smoothing

<b>Expected Output:</b>

```
sentence= ['i', 'love', 'you']

i love

bigram count for "i love" = ?
unigram count for "i" = ?
bigramProbability for "i love" = ?

love you

bigram count for "love you" = ?
unigram count for "love" = ?
bigramProbability for "love you" = ?

sentenceProbability for "i love you" = ?

sentence= ['i', 'hate', 'you']

i hate

bigram count for "i hate" = ?
unigram count for "i" = ?
bigramProbability for "i hate" = ?

hate you

bigram count for "hate you" = ?
unigram count for "hate" = ?
bigramProbability for "hate you" = ?

sentenceProbability for "i hate you" = ?

probability("i love you")>probability("i hate you") is: [True,False]?

sentence= ['OOV1', 'OOV2']

OOV1 OOV2

bigram count for "OOV1 OOV2" = ?
unigram count for "OOV1" = ?
bigramProbability for "OOV1 OOV2" = ?

sentenceProbability for "OOV1 OOV2" = ?
```

In [30]:
def probability(sentence):

    sentence_list = sentence.split(" ")
    
    # part of the expected output
    print(f"sentence= {sentence_list}\n")

    probabilities = []

    for i in range(0, len(sentence_list)-1):
        
        section = sentence_list[i] + " " +sentence_list[i+1]

        # part of the expected output
        print(section+"\n")

        # https://stackoverflow.com/questions/31536835/extract-value-from-single-row-of-pandas-dataframe
        bigram_count = bigrams_df.loc[bigrams_df['bigram'] == section]['count'].values
        unigram_count = unigrams_df.loc[unigrams_df['unigram'] == sentence_list[i]]['count'].values

        # I had to add logic to avoid errors when the words are not found in the txt files
        # https://stackoverflow.com/questions/5086178/how-to-check-if-array-is-not-empty
        bigram_count = bigram_count[0] if bigram_count.size else 0
        unigram_count = unigram_count[0] if unigram_count.size else 0
       
        print(f"bigram count for \"{section}\" = {bigram_count}")
        print(f"unigram count for \"{sentence_list[i]}\" = {unigram_count}")

        # https://youtu.be/UyC0bBiZY-A?t=16 P(w_i | w_i-1) = count(W_i-1, w_i) / count(W_i-1)
        bigram_probability = bigram_count / unigram_count if unigram_count != 0 else 0
        print(f"bigramProbability for \"{section}\" = {bigram_probability}\n")

        probabilities = probabilities + [bigram_probability]


    """
    Example from chapter 3, bigram
    P(<s> i want english food </s>) =   P(i|<s>)*P(want|i)*P(english|want)*P(food|english)*P(</s>|food)
                                    =   0.25*0.33*0.0011*0.5*0.68
                                    =   0.000031
    """
    sentence_probability = 1
    for probability in probabilities:
        sentence_probability = sentence_probability * probability
    print(f"sentenceProbability for \"{sentence}\" {sentence_probability}\n")
    return sentence_probability

#TESTING
probA = probability("i love you")
brobB = probability('i hate you')
#probability("i love you")>probability("i hate you") is: [True,False]?
print(f'probability("i love you")>probability("i hate you") is: {probA>brobB}\n')
probability("OOV1 OOV2") # Test for OOV (Out Of Vocabulary) N-grams

sentence= ['i', 'love', 'you']

i love

bigram count for "i love" = 3979312
unigram count for "i" = 3086225277
bigramProbability for "i love" = 0.001289378332053626

love you

bigram count for "love you" = 5428714
unigram count for "love" = 201063526
bigramProbability for "love you" = 0.02699999402178991

sentenceProbability for "i love you" 3.481320725727335e-05

sentence= ['i', 'hate', 'you']

i hate

bigram count for "i hate" = 876611
unigram count for "i" = 3086225277
bigramProbability for "i hate" = 0.0002840398614232463

hate you

bigram count for "hate you" = 504048
unigram count for "hate" = 21274675
bigramProbability for "hate you" = 0.023692394830943365

sentenceProbability for "i hate you" 6.7295845445659906e-06

probability("i love you")>probability("i hate you") is: True

sentence= ['OOV1', 'OOV2']

OOV1 OOV2

bigram count for "OOV1 OOV2" = 0
unigram count for "OOV1" = 0
bigramProbability for "OOV1 OOV2" = 0

sentenceProbability for "OOV1 OOV2" 0

0

## Task 1.c

Copy the function from 1.b into a new code cell, and modify it such that it applies add-one smoothing. Your new function should also address the problem of underflow when computing a sentence Probability

In [33]:
"""
from the book:
3.6.1 Laplace Smoothing
The simplest way to do smoothing is to add one to all the n-gram counts, before we normalize them into probabilities. 

https://youtu.be/Hr6UWRwAIEQ?list=PLAUFqkTvH_MQ&t=73
"""

def probability(sentence):

    sentence_list = sentence.split(" ")
    
    # part of the expected output
    print(f"sentence= {sentence_list}\n")

    probabilities = []

    for i in range(0, len(sentence_list)-1):
        
        section = sentence_list[i] + " " +sentence_list[i+1]

        # part of the expected output
        print(section+"\n")

        # https://stackoverflow.com/questions/31536835/extract-value-from-single-row-of-pandas-dataframe
        bigram_count = bigrams_df.loc[bigrams_df['bigram'] == section]['count'].values
        unigram_count = unigrams_df.loc[unigrams_df['unigram'] == sentence_list[i]]['count'].values

        

        # I had to add logic to avoid errors when the words are not found in the txt files
        # https://stackoverflow.com/questions/5086178/how-to-check-if-array-is-not-empty
        bigram_count = bigram_count[0] if bigram_count.size else 0
        unigram_count = unigram_count[0] if unigram_count.size else 0
       
        print(f"bigram count for \"{section}\" = {bigram_count}")
        print(f"unigram count for \"{sentence_list[i]}\" = {unigram_count}")

        laplace_smoothing = 1
        V = len(unigrams_df)
        # idk if the laplace goes here or in the probability
        # the book computes the probability as 
        # P_laplace(Wn|Wn-1) = C(Wn-1 Wn) + 1 / sum_w (C(Wn-1 W) + 1) = C(Wn-1 Wn) + 1 / C(Wn-1) + V
        # https://youtu.be/UyC0bBiZY-A?t=16 P(w_i | w_i-1) = count(W_i-1, w_i) / count(W_i-1)
        bigram_probability = (bigram_count + laplace_smoothing) / (unigram_count + V)
        print(f"bigramProbability for \"{section}\" = {bigram_probability}\n")

        probabilities = probabilities + [bigram_probability]


    """
    Example from chapter 3, bigram
    P(<s> i want english food </s>) =   P(i|<s>)*P(want|i)*P(english|want)*P(food|english)*P(</s>|food)
                                    =   0.25*0.33*0.0011*0.5*0.68
                                    =   0.000031
    """
    sentence_probability = 1
    for probability in probabilities:
        sentence_probability = sentence_probability * probability
    print(f"sentenceProbability for \"{sentence}\" {sentence_probability}\n")
    return sentence_probability

#TESTING
probA = probability("i love you")
brobB = probability('i hate you')
#probability("i love you")>probability("i hate you") is: [True,False]?
print(f'probability("i love you")>probability("i hate you") is: {probA>brobB}\n')
probability("OOV1 OOV2") # Test for OOV (Out Of Vocabulary) N-grams

sentence= ['i', 'love', 'you']

i love

bigram count for "i love" = 3979312
unigram count for "i" = 3086225277
bigramProbability for "i love" = 0.001289239409583089

love you

bigram count for "love you" = 5428714
unigram count for "love" = 201063526
bigramProbability for "love you" = 0.026955311155076156

sentenceProbability for "i love you" 3.475184943869884e-05

sentence= ['i', 'hate', 'you']

i hate

bigram count for "i hate" = 876611
unigram count for "i" = 3086225277
bigramProbability for "i hate" = 0.00028400951051436537

hate you

bigram count for "hate you" = 504048
unigram count for "hate" = 21274675
bigramProbability for "hate you" = 0.023326953599795038

sentenceProbability for "i hate you" 6.625076673669102e-06

probability("i love you")>probability("i hate you") is: True

sentence= ['OOV1', 'OOV2']

OOV1 OOV2

bigram count for "OOV1 OOV2" = 0
unigram count for "OOV1" = 0
bigramProbability for "OOV1 OOV2" = 3.000003000003e-06

sentenceProbability for "OOV1 OOV2" 3.000003000003e-06

3.000003000003e-06

In [ ]:
#I need to test underflow, the core material suggests using log

# Task 2

Using the [bigram counts](https://www.norvig.com/ngrams/count_2w.txt) (bigrams_df), write a function that implements the Shannon visualisation method:

<!--<b>Expected Output:</b>-->

```
<s> I
    I want
        want to
             to eat
                eat Chinese
                    Chinese food
                            food </s>

I want to eat Chinese food
```

[Chapter 3, section 3.4](https://web.stanford.edu/~jurafsky/slp3/3.pdf) gives a detailed description of the Shannon Visualisation method; a screenshot of this section is provided below. If you can follow the logic applied to unigrams, then you should be able to apply the same logic to bigrams.

Note: given the large size of the bigrams data, the Shannon Visualisation sampling can continue for a long time; therefore, for initial testing, you could terminate the sampling early whenever a common word (e.g. “and”) is generated as the next new seed.

Extra Help: 
- The seed word can be any word, but let's stick to the default seed word `<S>`, which indicates the beginning of the sentence. 
- First, you need to retrieve a list of all the bigrams starting with `<S>`, and then <u>randomly select one of them according to its probability</u>. Understanding this last part is key! You have a probability space between 0 and 1, and each of the candidate bigrams covers <u>an interval in this space proportional to its frequency</u>. For example, the candidate bigram “`<S>` and” has a total frequency of 261891475, which translates to a probability of 0.031513. If you consider this bigram to be your first candidate, then you can assign the probability interval 0.0 to 0.031513 to it. There are 8640 bigrams in the dataset which start with `<S>` and you need to compute the probability intervals for all of them. 
- Then generate a random number between 0 and 1 and check to see which interval it falls into; that would be your chosen bigram.
- Pick the second word in the chosen bigram, and that would be your new seed word.
- This process should be repeated until you either reach `</S>` (indicating the end of the sentence) or come across a seed which does not exist in your list of bigrams (i.e. there is no bigram starting with this seed word).

In [ ]:
def ShannonVisualization(seed="<S>"):
    print("YOUR CODE HERE")